### ISSUE TITLE
SteamUpdater: Error: Download failed: http error 0

### ISSUE THREAD

**Issue by Cybroken** [markusforss/csgo-docker#1]
I wanted to use your image on Ubuntu 16.04 ( docker version 1.11.0 ), but it results in throwing an error:

> csgo_server_1 | Redirecting stderr to '/home/csgo/Steam/logs/stderr.txt'
csgo_server_1 | ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
csgo_server_1 | [  0%] Checking for available update...
csgo_server_1 | SteamUpdater: Error: Download failed: http error 0
csgo_server_1 | [  0%] Download Complete.
csgo_server_1 | [----] Verifying installation...
csgo_server_1 | [  0%] Downloading Update...
csgo_server_1 | [  0%] Checking for available update...
csgo_server_1 | SteamUpdater: Error: Download failed: http error 0
csgo_server_1 | [  0%] Download Complete.
csgo_server_1 | SteamUpdater: Error: Steam needs to be online to update.  Please confirm your network connection and try again.
csgo_server_1 | [  0%] !!! Fatal Error: Steam needs to be online to update.  Please confirm your network connection and try again.
csgo_server_1 | Redirecting stderr to '/home/csgo/Steam/logs/stderr.txt'
csgo_server_1 | ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
csgo_server_1 | [  0%] Checking for available update...
csgo_server_1 | SteamUpdater: Error: Download failed: http error 0
csgo_server_1 | [  0%] Download Complete.
csgo_server_1 | [----] Verifying installation...
csgo_server_1 | [  0%] Downloading Update...
csgo_server_1 | [  0%] Checking for available update...
csgo_server_1 | SteamUpdater: Error: Download failed: http error 0
csgo_server_1 | [  0%] Download Complete.
csgo_server_1 | SteamUpdater: Error: Steam needs to be online to update.  Please confirm your network connection and try again.
csgo_server_1 | [  0%] !!! Fatal Error: Steam needs to be online to update.  Please confirm your network connection and try again.
csgo_server_1 | /home/csgo/start.sh: line 7: ./srcds_run: No such file or directory
csgo_csgo_server_1 exited with code 127

I use it with docker-compose. The compose-file looks like this:
> csgo_server:
  build: ${DOCKER_IMAGES}/csgo/
  ports:
    - "27015:27015/udp"
    - "27015:27015/tcp"
    - "3478:3478/udp"
    - "4379:4379/udp"
    - "4380:4380/udp"
    - "26900-26902"
    - "26900-26902/udp"

Maybe you have any idea what I could do?

**Comment by markusforss** [comment]
I will look into it as soon as I have time (tonight or tomorrow).

**Comment by Cybroken** [comment]
`--security-opt seccomp=unconfined` did the trick! Now it works perfect :-) But don't ask me why :D
